version: '3.8'

services:
  # MongoDB Database
  mongodb:
    container_name: mongodb
    restart: always
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: 1234
    ports:
      - '27017:27017'
    volumes:
      - ./mongo-data:/data/db
    networks:
      - app-network

  # Question Service
  question-service:
    container_name: question-service
    restart: always
    build:
      context: ./backend/question-service
      dockerfile: Dockerfile
    ports:
      - '8082:8082'
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongo
      ME_CONFIG_MONGODB_ADMINPASSWORD: 1234
      ME_CONFIG_MONGODB_URL: mongodb://mongo:1234@mongodb:27017
    networks:
      - app-network
    depends_on:
      - mongodb
    command: ['npm','test']

networks:
  app-network:
    driver: bridge
