name: CI

on:
  push:
    branches:
      - CI-Docker

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build and run Docker containers
        run: |
            docker-compose -f docker-compose.test.yml up -d
            docker-compose -f docker-compose.test.yml ps

      - name: Wait for services to start
        run: sleep 30

      - name: Run tests
        run: docker exec question-service npm test

      - name: Stop and remove Docker containers
        run: docker-compose -f docker-compose.test.yml down
