name: CI

on:
  push:
    branches:
      - CI-Docker

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:latest
        env:
          MONGO_INITDB_ROOT_USERNAME: mongo
          MONGO_INITDB_ROOT_PASSWORD: 1234
        ports:
          - '27017:27017'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build and run Docker containers
        run: |
            docker-compose -f docker-compose.test.yml up -d
            docker-compose -f docker-compose.test.yml ps

      - name: Wait for services to start
        run: sleep 30

      - name: Run tests
        run: docker exec question-service npm test

      - name: Stop and remove Docker containers
        run: docker-compose -f docker-compose.test.yml down
