name: Docker Compose Test

on:
  push:
    branches:
      - CI-Docker
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:latest
        ports:
          - 3000:3000

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Compose
        run: |
          docker-compose -f docker-compose.test.yml up -d

      - name: Tear down Docker Compose
        run: docker-compose -f docker-compose.test.yml down
